[package]
name = "google-ddns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
log = "0.4.14"
pretty_env_logger = "0.4.0"
base64 = "0.13.0"

