version: '3.9'

services:
  app:
    build: .
    environment:
      - DDNS_USERNAME=test
      - DDNS_PASSWORD=test
      - DDNS_HOST=test.dev
      - DDNS_MINUTES_INTERVAL=120
    container_name: google-ddns
    volumes:
      - "/etc/localtime:/etc/localtime"
